---
repos:
    - repo: https://github.com/ambv/black
      rev: 21.10b0
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.29.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.3
      hooks:
          - id: isort
            args: [--profile, black]
    - repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
          - id: isort
            name: isort (python)
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0  # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.2.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]
